export enum IAuthActionTypes{
    INIT_LOGIN = 'INIT_LOGIN',
    LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL',
    LOGIN_FAILED = 'LOGIN_FAILED',
    INIT_FETCH_USER_DATA = 'INIT_FETCH_USER_DATA',
    FETCH_USER_DATA_SUCCESSFUL = 'FETCH_USER_DATA_SUCCESSFUL',
    FETCH_USER_DATA_FAILED = 'FETCH_USER_DATA_FAILED',
    LOGOUT = 'LOGOUT'
}